force-app/main/default/objects/Invite__c/Invite__c.object-meta.xml
<CustomObject>
    <description>Tracks invitations to Partner Events</description>
    <label>Invite</label>
    <nameField>
        <displayFormat>PEI-{000000}</displayFormat>
        <label>Invites Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invite__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Contact invited to Partner Event</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Invites</relationshipLabel>
    <relationshipName>Invites</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invite__c/fields/PartnerEvent__c.field-meta.xml
<CustomField>
    <fullName>PartnerEvent__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Partner Event the Contact is invited to</description>
    <label>Partner Event</label>
    <referenceTo>PartnerEvent__c</referenceTo>
    <relationshipLabel>Invites</relationshipLabel>
    <relationshipName>Invites</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invite__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the invitation response</description>
    <inlineHelpText>Status of the invitation response</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>pending</fullName>
                <default>true</default>
                <label>pending</label>
            </value>
            <value>
                <fullName>accepted</fullName>
            </value>
            <value>
                <fullName>declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PartnerEvent__c/PartnerEvent__c.object-meta.xml
<CustomObject>
    <description>Company hosted partner events are held on for partners and contacts.</description>
    <label>Partner Event</label>
    <nameField>
        <displayFormat>PE-{000000}</displayFormat>
        <label>Partner Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PartnerEvent__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <description>Capacity of the event. The maximum number of accepted invites.</description>
    <inlineHelpText>Capacity of the event. The maximum number of accepted invites.</inlineHelpText>
    <label>Capacity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PartnerEvent__c/fields/Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Date_Time__c</fullName>
    <description>The date and time of the event</description>
    <label>Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/PartnerEvent__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>A rich text description of the event.</description>
    <inlineHelpText>A rich text description of the event.</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/PartnerEvent__c/fields/Event_Name__c.field-meta.xml
<CustomField>
    <fullName>Event_Name__c</fullName>
    <description>Name of the event</description>
    <label>Event Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InviteRestResourceTest.cls
@isTest
public class InviteRestResourceTest {

	public static testmethod void testUpdateStatusHappyPath() {

		DateTime eventDate = DateTime.now().addDays(2);
        
        PartnerEvent__c testEvent = new PartnerEvent__c(
            Date_Time__c = eventDate,
            Description__c = 'Test event description',
            Event_Name__c = 'Test event name',
            Capacity__c = 5            
        );
        insert testEvent;
        
        List<Id> contactIdList = new List<Id>();
        
        Contact c = new Contact();
        c.FirstName = 'Test';
        c.LastName  = 'User1';
        c.email='contact1@example.com';
        insert c;

        Invite__c invite = new Invite__c(
        	PartnerEvent__c = testEvent.Id,
        	Contact__c = c.Id
        );
        insert invite;
        Id inviteId = invite.Id;


   		Test.startTest();
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/invite'; 
        req.params.put('id', invite.Id);
        req.params.put('status', 'accepted');
        req.httpMethod = 'PATCH';
        req.addHeader('Content-Type', 'application/json'); 
        RestContext.request = req;
        RestContext.response = res;
        InviteRestResource.updateStatus();
        System.debug('res: ' + res);
        System.assertEquals(200, res.statusCode);

        invite = (Invite__c) JSON.deserialize(res.responseBody.toString(), Invite__c.class);
        System.assertEquals('accepted', invite.Status__c);
        System.assertEquals(inviteId, invite.Id);
	   	Test.stopTest();   
	}

}