force-app/main/default/objects/Invite__c/Invite__c.object-meta.xml
<CustomObject>
    <description>Tracks invitations to Partner Events</description>
    <label>Invite</label>
    <nameField>
        <displayFormat>PEI-{000000}</displayFormat>
        <label>Invites Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invite__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the invitation response</description>
    <inlineHelpText>Status of the invitation response</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>pending</fullName>
                <default>true</default>
                <label>pending</label>
            </value>
            <value>
                <fullName>accepted</fullName>
            </value>
            <value>
                <fullName>declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InviteRestResource.cls
@RestResource(urlMapping='/invite')
global with sharing class InviteRestResource {
	
	@HttpPatch
    global static String updateStatus() {

	    RestRequest request = RestContext.request;

	    Map<String, Object> params = (Map<String, Object>)
	    	JSON.deserializeUntyped(request.requestbody.tostring());

	    if (! params.containsKey('id')) {
	    	return 'ERROR: Invite ID not given in request';
	    }

	    if (! params.containsKey('status')) {
	    	return 'ERROR: Invite status not given in request';
	    }

	    Id inviteId  = (Id) params.get('id');
	    Id status = (String) params.get('status');

	    Invite__c invite = new Invite__c(Id = inviteId, Status__c = status);
	    try {
	    	update invite;
	    } catch (DmlException e) {
	    	return 'ERROR: DML Exception occured when trying to update invite with ID '
	    		+ inviteId + ' and Status__c of \'' + status + '\'';
	    }

	    invite = [
	    	SELECT Status__c
	    	FROM Invite__c
	    	WHERE Id = :inviteId
	    ];

	    return invite.Status__c;
    }
}