force-app/main/default/objects/Invite__c/Invite__c.object-meta.xml
<CustomObject>
    <description>Tracks invitations to Partner Events</description>
    <label>Invite</label>
    <nameField>
        <displayFormat>PEI-{000000}</displayFormat>
        <label>Invites Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invite__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Contact invited to Partner Event</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Invites</relationshipLabel>
    <relationshipName>Invites</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invite__c/fields/PartnerEvent__c.field-meta.xml
<CustomField>
    <fullName>PartnerEvent__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Partner Event the Contact is invited to</description>
    <label>Partner Event</label>
    <referenceTo>PartnerEvent__c</referenceTo>
    <relationshipLabel>Invites</relationshipLabel>
    <relationshipName>Invites</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invite__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the invitation response</description>
    <inlineHelpText>Status of the invitation response</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>pending</fullName>
                <default>true</default>
                <label>pending</label>
            </value>
            <value>
                <fullName>accepted</fullName>
            </value>
            <value>
                <fullName>declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PartnerEvent__c/PartnerEvent__c.object-meta.xml
<CustomObject>
    <description>Company hosted partner events are held on for partners and contacts.</description>
    <label>Partner Event</label>
    <nameField>
        <displayFormat>PE-{000000}</displayFormat>
        <label>Partner Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PartnerEvent__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <description>Capacity of the event. The maximum number of accepted invites.</description>
    <inlineHelpText>Capacity of the event. The maximum number of accepted invites.</inlineHelpText>
    <label>Capacity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PartnerEvent__c/fields/Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Date_Time__c</fullName>
    <description>The date and time of the event</description>
    <label>Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/PartnerEvent__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>A rich text description of the event.</description>
    <inlineHelpText>A rich text description of the event.</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/PartnerEvent__c/fields/Event_Name__c.field-meta.xml
<CustomField>
    <fullName>Event_Name__c</fullName>
    <description>Name of the event</description>
    <label>Event Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InviteTriggerTest.cls
@isTest
public class InviteTriggerTest {

    public static testmethod void testInvitationLimiting() {

        DateTime eventDate = DateTime.now().addDays(1);
        
        PartnerEvent__c testEvent = new PartnerEvent__c(
            Date_Time__c = eventDate,
            Description__c = 'Test event description',
            Event_Name__c = 'Test event name',
            Capacity__c = 2            
        );
        insert testEvent;

        List<Contact> contactList = new List<Contact>();
        for (Integer i = 1; i < 4; i++) {
            Contact c = new Contact(
                FirstName = 'Test',
                LastName  = 'User' + i,
                Email='contact' + i + '@example.com'
            );
            contactList.add(c);
        }
        insert contactList;

        List<Invite__c> inviteList = new List<Invite__c>();
        for (Contact c : contactList) {
            Invite__c invite = new Invite__c(
                PartnerEvent__c = testEvent.Id,
                Contact__c = c.Id
            );
            inviteList.add(invite);
        }
        insert inviteList;

        Test.startTest();

        for (Invite__c invite : inviteList) {
            invite.Status__c = 'accepted';
        }
        update inviteList;

        Test.stopTest();

        inviteList = [
            SELECT Status__c
            FROM Invite__c
            WHERE PartnerEvent__c = :testEvent.Id
        ];

        Integer acceptedCount = 0;
        Integer declinedCount = 0;
        for (Invite__c invite : inviteList) {
            if (invite.Status__c == 'accepted') {
                acceptedCount += 1;
            } else if (invite.Status__c == 'declined') {
                declinedCount += 1;
            }
        }

        System.assertEquals(2, acceptedCount);
        System.assertEquals(1, declinedCount);

    }

    public static testmethod void testValidateInvite() {
        
        Test.startTest();
        DateTime eventDate = DateTime.now().addDays(2);
        
        PartnerEvent__c testEvent = new PartnerEvent__c(
            Date_Time__c = eventDate,
            Description__c = 'Test event description',
            Event_Name__c = 'Test event name',
            Capacity__c = 5            
        );
        insert testEvent;
        
        Contact c1 = new Contact(
            FirstName = 'Test',
        	LastName  = 'User1',
        	Email='contact1@example.com'
        );
        
        Contact c2 = new Contact();
        c2.firstName = 'Test';
        c2.LastName = 'User2';
        c2.Email = 'contact2@example.com';
        insert new List<Contact> { c1, c2 };


        
        Invite__c i1 = new Invite__c(
            PartnerEvent__c = testEvent.Id,
            Contact__c = c1.Id
        );
        
        Invite__c i2 = new Invite__c(
            PartnerEvent__c = testEvent.Id,
            Contact__c = c2.Id
        );
        
        insert new List<Invite__c> { i1, i2 };
        
        // Note multiple emails are sent at once
        // so there should only be a single invocation in this case
        Integer invocations = Limits.getEmailInvocations();
        Test.stopTest();
        
        System.assertEquals(1, invocations);
    }    
}