force-app/main/default/objects/PartnerEvent__c/PartnerEvent__c.object-meta.xml
<CustomObject>
    <description>Company hosted partner events are held on for partners and contacts.</description>
    <label>Partner Event</label>
    <nameField>
        <displayFormat>PE-{000000}</displayFormat>
        <label>Partner Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PartnerEvent__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <description>Capacity of the event. The maximum number of accepted invites.</description>
    <inlineHelpText>Capacity of the event. The maximum number of accepted invites.</inlineHelpText>
    <label>Capacity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PartnerEvent__c/fields/Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Date_Time__c</fullName>
    <description>The date and time of the event</description>
    <label>Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/PartnerEvent__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>A rich text description of the event.</description>
    <inlineHelpText>A rich text description of the event.</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/PartnerEvent__c/fields/Event_Name__c.field-meta.xml
<CustomField>
    <fullName>Event_Name__c</fullName>
    <description>Name of the event</description>
    <label>Event Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EmailHelperTest.cls
@isTest
public class EmailHelperTest {
    // See: https://apexandbeyond.wordpress.com/2017/07/30/unit-testing-code-that-sends-email/
    // for info on testing email
    
    public static testmethod void testValidateEmailHelper() {
        
        Test.startTest();
        DateTime eventDate = DateTime.now().addDays(2);
        
        PartnerEvent__c testEvent = new PartnerEvent__c(
            Date_Time__c = eventDate,
            Description__c = 'Test event description',
            Event_Name__c = 'Test event name',
            Capacity__c = 5            
        );
        insert testEvent;
        
        List<Id> contactIdList = new List<Id>();
        
        Contact c = new Contact();
        c.FirstName = 'Test';
        c.LastName  = 'User1';
        c.email='contact1@example.com';
        insert c;
        contactIdList.add(c.Id);
        
        Contact c2 = new Contact();
        c2.firstName = 'Test';
        c2.LastName = 'User2';
        c2.Email = 'contact2@example.com';
        insert c2;
        contactIdList.add(c2.Id);
        
        Map<Id, List<Id>> eventContactMap = new Map<Id, List<Id>>();
        eventContactMap.put(testEvent.Id, contactIdList);
        
        List<Messaging.SendEmailResult> results = EmailHelper.sendInviteEmail(eventContactMap);

        // Note - multiple emails are sent at once - so there should only be a single invocation in this case.
        Integer invocations = Limits.getEmailInvocations();
        Test.stopTest();
        
        System.assertEquals(1, invocations);
        System.assertEquals(2, results.size());
        for (Messaging.SendEmailResult result : results) {
            System.debug('result: ' + result);
			System.assert(result.success);
        }
    }
}